############################
####### ANNIHILATION #######
#### MADE BY MASON PREY ####
###########################

# Enter true if you wish to run Annihilation with Bungee Servers (only one game per server instance)
bungee_mode: false

###########################
######### DATABASE ########
###########################
database:

    # Enter true if you want to use a MySQL database, or else the plugin will use flat-file (YAML) storage
    use_mysql: false

    # MySQL database information
    mysql:

        # Hostname for MySQL server
        host:

        # Username for user with all permissions for the database
        username:

        # Password for the username above
        password:

        # Database that the plugin will run off of
        database:

        # Port to connect to the server
        port:

        # Time (miliseconds) before a connection will timeout
        timeout: 5000

        # Minimum number of connections to the server for pooling (DO NOT CHANGE IF YOU DO NOT UNDERSTAND)
        min_connections: 2

        # Maximum number of connections to the server for pooling (DO NOT CHANGE IF YOU DO NOT UNDERSTAND)
        max_connections: 6


###########################
### REGENERATING BLOCKS ###
###########################
regen_blocks:

    # Time interval between checking respawning blocks in long units (DO NOT CHANGE IF YOU DO NOT UNDERSTAND)
    interval: 10

    # List of blocks
    blocks:

        # Each category must be uniquely named (any name is fine as long as it is not repeated)
        coal_ore:

            # Block to be mined
            type: COAL_ORE

            # Item given either dropped naturally or placed into player's inventory when 'type' is mined
            # Enter '0' in 'reward_amount' if you want no reward given
            reward: COAL

            # Number of items that are given of rewards
            # Enter '0' if you want no reward given
            reward_amount: 1

            # Delay in seconds between the block regenerating
            delay: 10

            # (True/false) Specify whether the reward should drop naturally on the block's location or into the player's inventory
            natural_drop: false

            # Block that replaces the 'type' field when mined
            place_holder: COBBLESTONE

            # Exp reward for mining the block
            # Enter 0 if you want to reward
            exp_reward: 5

            # Sound to be played when the block is mined
            # Enter 'NONE' if you want no sound to be played
            sound: ORB_PICKUP

            # Custom effects played when the block is mined
            # Current list of effects:
            # - GRAVEL
            # - NONE
            effect: NONE


